### ISSUE TITLE
Replace 'context_length' with 'num_ctx' to prevent warnings in ollama console

### ISSUE THREAD

**Issue by havenvanheusen** [TheBlewish/Automated-AI-Web-Researcher-Ollama#11]
https://github.com/TheBlewish/Automated-AI-Web-Researcher-Ollama/blob/c3c29a5da5d15dafbe1d4520f2a6527e60ffd3d3/llm_wrapper.py#L47

Changing context_length to num_ctx on line 47 of llm_wrapper.py resolves the following warning when requesting ollama to generate a response: 

`Nov 20 11:03:28 AI-VM ollama[1429718]: time=2024-11-20T11:03:28.234-06:00 level=WARN source=types.go:509 msg="invalid option provided" option=context_length`

Might fix the need to increase the context length of the ollama model with a modelfile. Ollama will override the model's default context length with the one sent by the request according to their documentation but I haven't tested it. 

https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-specify-the-context-window-size

**Comment by TheBlewish** [comment]
yeah it's in the instructions in the github to increase the context in the model file, thanks i'll update the code as you suggested.
For some reason the context length defaults to like 2k unless you increase it with the model file

**Comment by TheBlewish** [comment]
but yeah the context settings don't change anything unless you use the modelfile to do it for some reason unfortunately.
