### ISSUE TITLE
Termios not windows compatible?

### ISSUE THREAD

**Issue by nigelp** [TheBlewish/Automated-AI-Web-Researcher-Ollama#13]
Getting this error:

D:\researcher\Automated-AI-Web-Researcher-Ollama>python Web-LLM.py
Traceback (most recent call last):
  File "D:\researcher\Automated-AI-Web-Researcher-Ollama\Web-LLM.py", line 12, in <module>
    from research_manager import ResearchManager
  File "D:\researcher\Automated-AI-Web-Researcher-Ollama\research_manager.py", line 17, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'

**Comment by nigelp** [comment]
Sigh. I just wish... :) I'm just slogging through installing a bunch of stuff which seems to have failed to install. Not sure I've got the patience. Heh.

**Comment by dondiegorivera** [comment]
It runs perfectly on Win11:WSL mode. Start WSL, setup a Python env, install Ollama Linux, connect VS Code with WSL Plugin, clone the repo, and setup the script as described in the readme.

**Comment by nigelp** [comment]
I'm on Windows 10.

**Comment by 33lectric33l** [comment]
There is a PR for a windows compatible version, but it only addresses one of the modules

**Comment by nigelp** [comment]
It's a shame there's not a fully compatible version, because it looks like an interesting project.

**Comment by dondiegorivera** [comment]
You can install WSL on Win10 too. https://contabo.com/blog/how-to-install-wsl2-on-windows-10/

**Comment by nigelp** [comment]
Not really that keen, actually. Huge space hog etc.

**Comment by scaruslooner** [comment]
Damn i just ranned into the same issue :(. I dont want to install WSL

**Comment by scaruslooner** [comment]
Im getting this error now:
(env) Z:\AI\Scar\Automated Web Researcher>python Web-LLM.py
Traceback (most recent call last):
  File "Z:\AI\Scar\Automated Web Researcher\Web-LLM.py", line 8, in <module>
    from Self_Improving_Search import EnhancedSelfImprovingSearch
ImportError: cannot import name 'EnhancedSelfImprovingSearch' from 'Self_Improving_Search' (Z:\AI\Scar\Automated Web Researcher\Self_Improving_Search.py)

**Comment by nigelp** [comment]
Nope, no change at all. Still curses issue and all the rest. It's completely broken on Windows.

**Comment by nigelp** [comment]
Hi @hafeezhmha, thanks very much for your help. Unfortunately I am not getting anywhere with this project. I don't have time or energy to debug it on Windows right now. I would hope, that like many other Github projects of this type, the author would ensure that the requirements, dependencies and other critical elements just work as advertised. 

It's not just one thing, there's a large list of things that break when I follow the Readme instructions, the curses thing is just one of many. It's not hard surely to test and iterate until something works? I don't mind helping to enhance something, but it would be nice to have it working at least in a basic form out of the box. 

I don't want to sound churlish, because it's great for someone to offer this to the community, and it is appreciated.

**Comment by TheBlewish** [comment]
Yeah there is now a windows branch of the program, which should work! yeah windows its hard to work out the box although easier now with the windows branch (I assume I don't have windows and [hafeezhmha](https://github.com/hafeezhmha) kindly provided the windows version which is now a new branch on the main program)
