### ISSUE TITLE
Could not find a version that satisfies the requirement curses-windows

### ISSUE THREAD

**Issue by ninjaeon** [TheBlewish/Automated-AI-Web-Researcher-Ollama#15]
When running pip install -r requirements.txt on Windows 11 I get the following error:

ERROR: Could not find a version that satisfies the requirement curses-windows (from versions: none)
ERROR: No matching distribution found for curses-windows

Updating the line in requirements.txt from curses-windows; sys_platform == 'win32' to **windows-curses**; sys_platform == 'win32' fixes the issue and pip install -r requirements.txt completes without errors.

https://github.com/TheBlewish/Automated-AI-Web-Researcher-Ollama/pull/8/commits/b60ee52947d39d9659e1856fd9258ab5c63a6765

**Comment by mcihb** [comment]
This might help: https://stackoverflow.com/questions/77423447/cant-install-curses-package

**Comment by TheBlewish** [comment]
> This might help: https://stackoverflow.com/questions/77423447/cant-install-curses-package

Thanks mate! i've been busy with Uni please let me know if it fixes it!

**Comment by mcihb** [comment]
It did seem to fix it for me, however after completing installation i get the same error but for a different python module i think? (I unfortunately dont have programming experience so im kind of winging it as usual) Error: 

PS X:\AI Models\System AI\Automated-AI-Web-Researcher-Ollama> python Web-LLM.py
Traceback (most recent call last):
  File "X:\AI Models\System AI\Automated-AI-Web-Researcher-Ollama\Web-LLM.py", line 12, in <module>
    from research_manager import ResearchManager
  File "X:\AI Models\System AI\Automated-AI-Web-Researcher-Ollama\research_manager.py", line 17, in <module>
    import termios
ModuleNotFoundError: No module named 'termios'
PS X:\AI Models\System AI\Automated-AI-Web-Researcher-Ollama> pip install termios
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement termios (from versions: none)
ERROR: No matching distribution found for termios

**Comment by hafeezhmha** [comment]
@TheBlewish hahahah! I have left it running too for some research. Great work on the project mate, I love opensource and this is amazing!
Also I am updating it as i come across any errors. So if something doesn't work, add issues, check the repo out as well, as it might be updated!

**Comment by hafeezhmha** [comment]
@lascimmia the issue is most probably with the python version. 3.13 is still not compatible with many libraries. I'd recommend you to create a virtual env and install 3.11 and then set up the project

**Comment by synth-mania** [comment]
Interesting. Python 3.13 works just fine for me on linux.

**Comment by hafeezhmha** [comment]
@synth-mania 
I have not tested it with 3.13 on windows yet.

See if you can install windows-curses without specifying the version.

**Comment by lascimmia** [comment]
>     * If it still doesn't work, you can just install
> 
> 
> pip install windows-curses
> 
> Without specifying the version number.

Thanks a lot, I'll downgrade my Python venv.
By the way, installing windows-curses on 3.13 does not work at all

**Comment by mcihb** [comment]
> @mcihb ahh so many people wanna try this on windows. I have made a windows implementation of this project, here : https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama.git
> 
> You can check it out if you want to! I am still working on it, for now its running!



> wow it's running! Good job! Great work honestly I doubted it was possible I don't have windows so there was no way I could do it!
> 
> > @mcihb ahh so many people wanna try this on windows. I have made a windows implementation of this project, here : https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama.git
> > You can check it out if you want to! I am still working on it, for now its running!

I have gotten it up and running! Thanks @hafeezhmha for the effort in porting this to windows, also thanks to @TheBlewish for creating this! I will be exploring the capabilities of it using qwen2.5-14b, Currently running a research query!

**Comment by synth-mania** [comment]
I've also tried with Qwen2.5. Definitely gets the job done, but I think that the actual search queries being sent to duckduckgo could be improved. I'll make an issue @mcihb 

I'm sure you've noticed as I have the inclusion of irrelevant sources as well.

**Comment by mcihb** [comment]
> I've also tried with Qwen2.5. Definitely gets the job done, but I think that the actual search queries being sent to duckduckgo could be improved. I'll make an issue @mcihb
> 
> I'm sure you've noticed as I have the inclusion of irrelevant sources as well.

Most definitely, I was however impressed with qwens ability to sort through the useless information without adding information from those irrelevant sources, Ill have to play around with it more when i have some free time.

**Comment by Cootz** [comment]
I'm pretty sure the package was called `windows-curses` not `curses-windows`
![image](https://github.com/user-attachments/assets/55c4f630-7934-4d14-938b-861ada3a5a74)

**Comment by Liu8Can** [comment]
> @mcihb ahh so many people wanna try this on windows. I have made a windows implementation of this project, here : https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama.git@mcihb ahh so many people wanna try this on windows. I have made a windows implementation of this project, here : https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama.git@mcihb啊，这么多人想在 Windows 上尝试这个。我已经完成了这个项目的 Windows 实现，这里 ： https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama.git
> 
> You can check it out if you want to! I am still working on it, for now its running!You can check it out if you want to! I am still working on it, for now its running!如果你愿意，你可以去看看！我还在努力，现在它正在运行！

That's cool. I will check it thanks!

**Comment by tingao** [comment]
Ok, very simple solution...
Just make sure to change the requirements.txt file than run python 3.11.

1. Change the requirements.txt from 


```
keyboard
**curses-windows**; sys_platform == 'win32'
tqdm
urllib3
```


to

```
keyboard
**windows-curses**; sys_platform == 'win32'
tqdm
urllib3
```


3. Commands to run on python version 3.11 (after you have installed python 3.11 from here https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe)

py -3.11 -m venv venv
venv\Scripts\activate
pip install -r requirements.txt

**Comment by hafeezhmha** [comment]
@TheBlewish Can you check the discussions tab.

**Comment by synth-mania** [comment]
@sebkont you will probably want to know this: we have a new branch on the repo now with windows support. I don't have a windows PC I can use for this, but please try it out and let us know if there are any issues!

**Comment by TheBlewish** [comment]
Yeah there is a new branch with windows support! Thanks guys!
