### ISSUE TITLE
Out of memory with phi3:3.8b-mini-128k-instruct

### ISSUE THREAD

**Issue by paviko** [TheBlewish/Automated-AI-Web-Researcher-Ollama#18]
OS: Debian 12
Running only on CPU, 128GB RAM

When starting Web-LLM.py i'm getting error: Ollama API request failed with status 500: {"error":"model requires more system memory (98.8 GiB) than is available (96.8 GiB)"

The model is "_phi3:3.8b-mini-128k-instruct-q4_K_M_" and is created as described:
FROM phi3:3.8b-mini-128k-instruct-q4_K_M
PARAMETER num_ctx 38000

When using _ollama run phi3:3.8b-mini-128k-instruct-q4_K_M_ it takes only 5GB RAM
When using _ollama run research-phi3_ (just created from modelfile) it takes 50GB RAM

Anyone has idea why it need 50GB when started aside and even 100GB when using Web-LLM?

**Comment by TheBlewish** [comment]
Try restarting in all my testing this happened to me once, also when you made it from the model file try to decrease the context size a little bit if it's a problem that isn't solved by restart. In my experience my restart fixed it, but my computers weird, but based on the error message you only need like a couple gigs more so if you decrease the context in the model file slightly it'll probably fix it!
