### ISSUE TITLE
How can I use this project via ChatGPT's API instead of Ollama?

### ISSUE THREAD

**Issue by endNone** [TheBlewish/Automated-AI-Web-Researcher-Ollama#20]

**Comment by synth-mania** [comment]
This could cost a lot of money to leave running if you are using a paid API

**Comment by benx13** [comment]
check pr #22

**Comment by nightscape** [comment]
and also https://github.com/TheBlewish/Automated-AI-Web-Researcher-Ollama/pull/1

**Comment by synth-mania** [comment]
@nightscape Well that sucks. Wasn't expecting @TheBlewish to want to kneecap their own project like that.

@endNone just use @nightscape 's fork for now I guess

**Comment by nightscape** [comment]
It's not my fork, I'm just using it on my machine 😉 
But yeah, the fork works well with LM Studio.

**Comment by TheBlewish** [comment]
> This could cost a lot of money to leave running if you are using a paid API

This is one of my prime concerns given the whole point is to do heaps of searches.

> Well that sucks. Wasn't expecting @TheBlewish to want to kneecap their own project like that.
> 
> @endNone just use the fork for now I guess https://github.com/NimbleAINinja/Automated-AI-Web-Researcher-Hosted

Hey I am not trying to knee cap my own project, I have like 2 exams for Uni today and have just been trying to reply as best I can to stuff while studying frantically.

Also none of the pull requests from what I can tell actually would even work! 

like throwing in some stuff into the config and wrapper scripts about OpenAI I really doubt is going to be sufficient, to make it actually work, and it's also concerning that someone without realizing could spend heaps of money on API calls without realizing it which would suck.

But that being said, please if you wanna make this open a discussion in the discussions tab, and show that it works! And if you do I will merge the pull request as long as it doesn't harm the Ollama functionality of the program!

**Comment by TheBlewish** [comment]
> It's not my fork, I'm just using it on my machine 😉 But yeah, the fork works well with LM Studio.

Sorry I only just saw this, I have to do my exams but rest assured everyone after that I will look into this, if it works well I will merge it as long as it doesn't harm Ollama functionality if y'all could make a discussion with the details that would still really help thanks!

**Comment by synth-mania** [comment]
Yeah, I don't think many of us are concerned with using web APIs specifically, it's just we all have our preferred hosting platforms @TheBlewish

**Comment by synth-mania** [comment]
I may have gotten the wrong idea, I was under the impression you were against adding openAI API support period

**Comment by TheBlewish** [comment]
Haha, yeah no I am all for it I just want to make sure it works so that we don't have redundant code that isn't viable, let me know if there's something like that which is functioning, Night scape said there was one that worked well? Can you maybe confirm for me if you get a second? I'll have to check it later though, thanks mate!

**Comment by synth-mania** [comment]
@TheBlewish I'm about to clone the fork @nightscape was referring to. I'll tag you with my findings under the pull request from the fork author

**Comment by benx13** [comment]
> Haha, yeah no I am all for it I just want to make sure it works so that we don't have redundant code that isn't viable, let me know if there's something like that which is functioning, Night scape said there was one that worked well? Can you maybe confirm for me if you get a second? I'll have to check it later though, thanks mate!

technically for redundancy you could remove all other libraries and use the openai api with all other endpoints such as Ollama llama file .... tested it yesterday with gpt-4o-mini works quite well and expensive to run 0.6$ per million tokens, the reason cloud is better than local is generation speed rather than low cost besides you could multithread it with cloud which is highly unlikely with local models (latency)

**Comment by TheBlewish** [comment]
Hey Guys! it has been updated now and it should work with the OpenAI API I tested it myself on LM studio and it works! Sorry for the delay!
