### ISSUE TITLE
Stuck after scraping papers

### ISSUE THREAD

**Issue by lihaoxin2020** [TheBlewish/Automated-AI-Web-Researcher-Ollama#24]
Hi, 

Thanks for the great work! 

In my experience the bot stuck while searching. Screenshot attached below. 
what could be the bottleneck? GPUs seem not involved in this process. 

thanks! 

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/f9f1f6fe-94ad-40ac-8735-e9e5defdeb8f">

**Comment by slyfox1186** [comment]
If you have any experience with pytest you might utilize it to get you HQ error reports.

**Comment by TheBlewish** [comment]
like it would just stay on that screen? Not doing anything? I have never seen that despite the heaps of testing I did with it! What does it say when you do the s command?

**Comment by slyfox1186** [comment]
I am on Windows 11 WSL 2 Ubuntu 24.04. Lets start there. And I will see if I can get you any more as soon as I can.

**Comment by synth-mania** [comment]
I actually may have run into a similar issue once. The program runs mostly fine on my RTX 3090 workstation, but on my 16gb RAM laptop even though the model loaded it would not generate any research summary, despite listing sources etc. Curious.

**Comment by lihaoxin2020** [comment]
i'm running on dual 4090 wsl2 with RAM 24G. Mem could be an issue but I'm not sure. 

> like it would just stay on that screen? Not doing anything? I have never seen that despite the heaps of testing I did with it! What does it say when you do the s command?
<img width="789" alt="Screenshot 2024-11-21 at 11 39 34 PM" src="https://github.com/user-attachments/assets/d0fad085-7736-44cf-a8d0-28631fc27d1e">

@TheBlewish it does move after a long while, sometimes fail to scraped the webpage and sometimes take another long while to search like above. 

@slyfox1186 @synth-mania Thanks guys! pls lmk if you find anything else relevant

**Comment by TheBlewish** [comment]
Yeah well windows is not really fully supported yet, a kind individual is in the process of making a windows compatible version right now that i'll send you a link to when it's ready

**Comment by gokulcoder7** [comment]
I got similar problem
