### ISSUE TITLE
termios is linux only

### ISSUE THREAD

**Issue by IDKaccountFlagged** [TheBlewish/Automated-AI-Web-Researcher-Ollama#3]
Can't run on windows, since termios is only available on linux. Didn't try WSL, might work on that.

**Comment by TheBlewish** [comment]
Yeah sorry mate! I only have Linux and unfortunately I have no way to test on windows easily, so i'm afraid I can't really help you there my apologies!

**Comment by hafeezhmha** [comment]
Hey @IDKaccountFlagged 
Here's the windows implementation, 
https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama/tree/main
check it out and let me know if you find any issue!
