### ISSUE TITLE
[Feature Request] Can it be extended to local documents

### ISSUE THREAD

**Issue by Curiosity007** [TheBlewish/Automated-AI-Web-Researcher-Ollama#31]
Idea is to use local documents as it's knowledge source, and then use local and web for a final report. 

Use case - 

A highly specialised academic report which will require few unpublished PDFs and few web searches to compliment few things.

**Comment by synth-mania** [comment]
May as well implement a whole RAG system then for the local files lol

Good idea.

**Comment by TheBlewish** [comment]
If someone wants to make this and suggest a pull request then sure! But I don't really have the time to do it right now!
