### ISSUE TITLE
Socket address issue?

### ISSUE THREAD

**Issue by warnakey** [TheBlewish/Automated-AI-Web-Researcher-Ollama#36]
I THINK I have followed all the steps to set this up correctly, but when I run "ollama serve" it says, "Error: listen tcp 0.0.0.0:11434: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted."

I have no idea what to do to solve this. I've tried restarting Ollama and restarting my computer and playing around with the config, but I can't get it to work. I am on windows 11.

**Comment by leapingturtlefrog** [comment]
This likely means you already have Ollama running or another process is using that socket.

Run in a command line (may need to be admin)
`netstat -ano | findstr :11434`

The last value in the output will be the process ID, something like this:
`TCP    0.0.0.0:11434    0.0.0.0:0    LISTENING    <PID>`
(If it is blank that means that there is no process running there)

Use that value in `tasklist | findstr <PID>` to show what is being run on that socket.

It will probably show Ollama but if does not you can kill the other process running there:
`taskkill /PID <PID> /F`

Here's a screenshot:
<img width="862" alt="image" src="https://github.com/user-attachments/assets/8b640286-9f35-4973-91de-48907d0fb623">

**Comment by leapingturtlefrog** [comment]
An easier way is to also check your taskbar in the bottom right:

<img width="295" alt="image" src="https://github.com/user-attachments/assets/461d2102-11d4-40f7-a73b-a2a436ae6e1b">

**Comment by warnakey** [comment]
I just tried it again today and here is what my Terminal looks like

![stuck](https://github.com/user-attachments/assets/50017b33-1267-4629-bc37-d4daa9ab8717)

It basically gets stuck here forever and never updates. So, when I try a 2nd time to run it, it does get past this screen and shows the error message about socket addresses.

When I tried the netstat PID thing, the process that was running was indeed Ollama. I'm still clueless on how to use this thing.

It's kind of a complicated setup for a beginner. I've spent over 3 hours on this already.

**Comment by leapingturtlefrog** [comment]
Your screenshot shows that Ollama started and the server is running. That's all it's supposed to show.

Open a new terminal and run `ollama list` for example and you'll see the ping in your first terminal.

Here's my two terminals:
<img width="871" alt="image" src="https://github.com/user-attachments/assets/a54fcc1a-5d53-40f6-b0a1-3bd62bf092b7">

But this is just Ollama stuff. To run AI Web Researcher on Windows check out this repo (the one you're commenting on is only for Unix systems right now):
[github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama](https://github.com/hafeezhmha/Automated-AI-Web-Researcher-Ollama)

Cheers.

**Comment by synth-mania** [comment]
@leapingturtlefrog Shouldn't they be able to get this working on Windows using WSL either way?

**Comment by leapingturtlefrog** [comment]
@synth-mania Yeah you're right; it was more of an Ollama question that would have happened on WSL or Windows. I'll edit my response to point towards WSL instead.

**Comment by warnakey** [comment]
Thank you all. I was finally able to get it running. Now to figure out what the heck I am doing with it. It only seems to want to give me quick summaries instead of detailed answers. Hmmmmm...........

I'll mark this as closed.
