### ISSUE TITLE
Please Add Kagi Search Engine as a Provider

### ISSUE THREAD

**Issue by ylluminate** [TheBlewish/Automated-AI-Web-Researcher-Ollama#37]
Kagi's a highly advanced search engine offering exceptional result quality with features like precise ranking algorithms, recency sorting, and the ability to prioritize "small web" content. Adding Kagi would significantly enhance the research assistant's ability to find actionable and relevant information efficiently.

**Key Benefits:**  
- **High-Quality Results:** Optimized for actionable and relevant information.  
- **Curated and Targeted Searches:** Reduces noise and filters results for smaller, more authoritative sources.  
- **Advanced Features:** Inline filtering and recency sorting to enhance research precision.  
- **Stable and Reliable Performance:** Consistent output for diverse research topics.  

This integration will further *REALLY* elevate the research assistant's ability to deliver quality, highly relevant, and accurate results across varied queries, making it a more powerful and versatile tool.

**Comment by TheBlewish** [comment]
Hey if you want to incorporate this stuff suggest an update to the code of the feature/multi-api-search branch, and implement it! use a pull request and i'll test it and merge it with that branch, should it seem viable!
