### ISSUE TITLE
Add SearX Search Engine with Instance Support

### ISSUE THREAD

**Issue by ylluminate** [TheBlewish/Automated-AI-Web-Researcher-Ollama#38]
**Description:**  
SearX is an open-source meta-search engine that aggregates results from many search engines, offering extensive customization and curation capabilities. The instance at searx.tiekoetter.com provides a really robust platform for personalized search preferences, which can be integrated using the "Search URL of the currently saved preferences" in the settings/preferences area where the cookie/settings are embedded into the URL. Adding this functionality would unlock significant flexibility for tailored research tasks and improve the variety of sources accessed by the assistant.

You'll find what I'm talking about in this area of preferences:
![image](https://p153.p0.n0.cdn.zight.com/items/lluABpNl/90a9be2e-db36-413c-b977-7ba69ec5ee17.png?v=c85c73e9088fd7fe70074db23dcc5db5)

**Key Benefits:**  
- **Customizable Curation:** Utilize user-specified preferences saved in SearX to refine search parameters dynamically.  
- **Wide Coverage:** Access results from multiple search engines in one query, maximizing information retrieval.  
- **Fine-Grained Filtering:** Leverage SearX’s advanced filtering options for more relevant and actionable results.  
- **Instance-Specific Optimization:** Tailor searches to the capabilities of the https://searx.tiekoetter.com/ instance, ensuring stability and performance.  

I think the main thing for configuration is to allow users to input the custom "Search URL of the currently saved preferences" into the configuration file, which would then in turn allow you to implement the assistant to dynamically append queries to the URL for each search request.

**Comment by TheBlewish** [comment]
Hey if you want to incorporate this stuff suggest an update to the code of the feature/multi-api-search branch, and implement it! use a pull request and i'll test it and merge it with that branch, should it seem viable!
