### ISSUE TITLE
Does not support Chinese for question retrieval.

### ISSUE THREAD

**Issue by Liu8Can** [TheBlewish/Automated-AI-Web-Researcher-Ollama#39]
![image](https://github.com/user-attachments/assets/d6e95acf-bb9b-451a-ae50-9548daf856e0)
I want to ask questions in Chinese, but I can only input in English.

**Comment by Liu8Can** [comment]
I tried to modify the `get_multilie_input()` method to solve this problem, but the content in research_session is still in English and some content is garbled. I am trying to solve it.
def get_multiline_input() -> str:
    """获取多行输入（按Ctrl+Z提交，支持中文输入）"""
    print(f"{Fore.GREEN}📝 请输入您的消息（按Ctrl+Z提交）：{Style.RESET_ALL}")
    lines = []
    current_line = []

    import msvcrt

    try:
        while True:
            if msvcrt.kbhit():
                char = msvcrt.getwch()  # 使用 getwch() 处理宽字符（支持中文）

                # Ctrl+Z检测（Windows EOF）
                if char == '\x1a':  # ASCII code for Ctrl+Z
                    sys.stdout.write('\n')  # 新行清理显示
                    if current_line:
                        lines.append(''.join(current_line))
                    return ' '.join(lines).strip()

                # 处理回车键（Enter）
                elif char in ['\r', '\n']:  
                    sys.stdout.write('\n')
                    lines.append(''.join(current_line))
                    current_line = []

                # 处理退格键（Backspace）
                elif char == '\x08':  
                    if current_line:
                        current_line.pop()
                        sys.stdout.write('\b \b')  # 删除字符

                # 处理Ctrl+C（退出）
                elif char == '\x03':  # Ctrl+C
                    sys.stdout.write('\n')
                    return 'q'

                # 普通字符（支持中文输入）
                elif 32 <= ord(char) <= 126 or 0x4e00 <= ord(char) <= 0x9fff:  # 允许输入中文
                    current_line.append(char)
                    sys.stdout.write(char)

                # 刷新输出
                sys.stdout.flush()

    except Exception as e:
        logger.error(f"多行输入发生错误: {str(e)}")
        return 'q'
![image](https://github.com/user-attachments/assets/394e78fe-8cb1-437a-a2c5-ec15fd45d617)

**Comment by Liu8Can** [comment]
In short, as long as non-English content appears in the retrieval results, there is a high probability that garbled characters will appear in the `session` file.

**Comment by TheBlewish** [comment]
Yeah I don't speak Chinese, and unfortunately as hard as it was to get it to work for English alone, I am not sure how it could be done with Chinese, 
Would it not be viable to say put a question in Chinese into google translate to English put that request into the English version, and then put all the content gathered into translate back to Chinese?

**Comment by Liu8Can** [comment]
> Yeah I don't speak Chinese, 和 unfortunately as hard as it was to get it to work for English alone, I am not sure how it could be done with Chinese, Would it not be viable to say put a question in Chinese into google translate to English put that request into the English version, 和 then put all the content gathered into translate back to Chinese?

OK. Thanks. Currently using English for search.
