### ISSUE TITLE
Ollama API request failed with status 404

### ISSUE THREAD

**Issue by cicero34** [TheBlewish/Automated-AI-Web-Researcher-Ollama#42]
This looks like an interesting package.  We have installed and can start the script running.  But then I get the following error message: System initialization failed: LLM test failed: Ollama API request failed with status 404: {"error":"model 'custom-phi3-32k-Q4_K_M' not found"}
The model running is phi3:medium-128k and that is entered in the modelfile as "FROM phi3:medium-128k".  Do we need to change the model or the modelfile in some way?

**Comment by synth-mania** [comment]
When you created the model with Ollama "ollama create model-name -f model-file", you specified a modelname. That should be entered into the llm_config.py

**Comment by leapingturtlefrog** [comment]
Specifically change these two lines and you should be good to go!

![image](https://github.com/user-attachments/assets/6ee14ed6-2ff5-4a10-840e-eb346dad4c21)

**Comment by cicero34** [comment]
Thanks for the quick responses.  I had not been looking at the llm_config.py file.  Now fixed!
