### ISSUE TITLE
Warning: Document size exceeded configured limit

### ISSUE THREAD

**Issue by dondiegorivera** [TheBlewish/Automated-AI-Web-Researcher-Ollama#45]
Hi,

Since the update the system fills the context window very fast, while creating a very small file. With the original version the research finished around 250-300k file size (I'm running it on a single 4090), now it finishes at 20k. 

Ollama is up-to-date, I tried with qwen2.5-7b-q6_K (6Gb) and phi3.5:3.8b-mini-instruct-q8_0  (4Gb), the issue appears with both. Ollama also offloads to CPU and claims 30GB memory for phi3.5:8b. It was not the case before. 

The n_ctx and context_length parameters are untouched and I did create the customizing model with ollama -f.

Anyone having the same issue? Any solutions?

Thanks a lot.

**Comment by synth-mania** [comment]
On a 4090, depending on the LLM you're running, you should be able to reliably support at least 80k token context size. I've been able to run 131k token context on my 3090 on smaller models too.

**Comment by dondiegorivera** [comment]
Thank you. I found the reason, it's not an issue, only a contraint configured in the system_config.py: the default for max_document_size is set to 12000 character.

**Comment by alex-crr** [comment]
I have a laptop 4070, the model ask me for 80 Gib of system memory with the specified context  length in the Readme? I tried reducing it still got the same error. Is it linked?

**Comment by synth-mania** [comment]
@alex-crr the modelfile is created only for configuring a model to run with ollama with the `ollama create modelname -f modelfile` command

**Comment by TheBlewish** [comment]
Yeah that system_config thing was because of an accidental merge I made which is fixed now redownload the github main for the original working version, that other new APIs version is now in a separate branch.
