### ISSUE TITLE
Getting 'list index out of range' error messages.

### ISSUE THREAD

**Issue by dpllpd** [TheBlewish/Automated-AI-Web-Researcher-Ollama#50]
Hi, 

Thanks for your work.

I'm getting a lot of these:

**searching: Company Profile and Financials
Error during search: list index out of range**

In fact it looks as if every search results in these.

-dpllpd

**Comment by synth-mania** [comment]
This is a duplicate issue
see: #44

**Comment by TheBlewish** [comment]
Hey everyone! 

Whoops, my bad! 😅 I totally messed up and accidentally merged some big changes that added a bunch of API stuff. This wasn't supposed to happen it wasn't in the description of the changes I should've been more careful!

I've rolled it back to how it was before so it should work like it used to - just Ollama and openAI end points, basic web scraping, no fancy API stuff needed.

If it's still acting weird, just reopen this issue or make a new one and let me know what's up. 

Sorry about that! goodness me!
