### ISSUE TITLE
Update documentation to update llm_config.py before running Web-LLM.py

### ISSUE THREAD

**Issue by kjenney** [TheBlewish/Automated-AI-Web-Researcher-Ollama#56]
The solution was given in https://github.com/TheBlewish/Automated-AI-Web-Researcher-Ollama/issues/42, but the documentation doesn't reflect this requirement. Please add a step under Installation or Usage to update llm_config.py with the custom model that was created.

**Comment by synth-mania** [comment]
@kjenney check out my changes to README.md in #53 

I agree that the setup process was a little confusing, so I made some changes in my PR that I think will make configuration much more clear.
