### ISSUE TITLE
 An issue where repeated requests yield no output, and the network environment is normal

### ISSUE THREAD

**Issue by endNone** [TheBlewish/Automated-AI-Web-Researcher-Ollama#58]
![1732693991659](https://github.com/user-attachments/assets/8bb5438c-ee32-481f-bdf2-3e06fe9a3d57)

**Comment by leapingturtlefrog** [comment]
Hmmm @TheBlewish @synth-mania how does it decide when to add content from a page or not? I wonder if it's deciding the content isn't relevant but it still fills up the context space.

**Comment by endNone** [comment]
I found the problem, it’s an issue with the version of DuckDuckGo.
