### ISSUE TITLE
Press P, and the screen goes blank. Press c for continue and screen stays blank. 

### ISSUE THREAD

**Issue by nigelp** [TheBlewish/Automated-AI-Web-Researcher-Ollama#59]
As the title says, the research bit goes well it seems, but then when you want to get a status or query, the screen just locks. Not sure if
![screenblack](https://github.com/user-attachments/assets/abe70064-a46f-4156-b81b-865291c60726)
 it runs out of memory or just hangs it's pretty frustrating

**Comment by leapingturtlefrog** [comment]
Did you submit the input through `Ctrl+d` (Linux, MacOS, WSL) or `Ctrl+z` (Windows)? Just pressing a key isn't enough, you have to submit it. Also, what happened when you did `q` and then `Ctrl+d` (or z) to stop the research?

**Comment by nigelp** [comment]
OK just tried again with CTRL-Z and letter and it still freezes. Am I supposed to be running this in a venv first?

**Comment by nigelp** [comment]
btw teh readme is wrong? teh correct argument for venv is venv\Scripts\activate (not venv/bin/activate)

**Comment by TheBlewish** [comment]
I assume this was fixed thanks! Please reopen if not!
